if has('nvim')
	let $NVIM_TUI_ENABLE_TRUE_COLOR=1
	let s:rc_dir = expand('$HOME') . '/.config/nvim'
else
	" vim と nvim でコンフィグファイルの置き場所がことなる
	let s:rc_dir = expand('$HOME') . '/.vim'
endif

let g:python3_host_prog = expand('$HOME') . '/.pyenv/shims/python3'
let g:python_host_prog = expand('$HOME') . '/.pyenv/shims/python2'

"dein Scripts-----------------------------
if &compatible
  set nocompatible               " Be iMproved
endif

let s:dein_dir = s:rc_dir . '/dein'
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'

" なければディレクトリ作成
if !isdirectory(s:dein_dir)
	execute '!mkdir -p ' . s:deia_dir
endif

" なければ git clone "
if !isdirectory(s:dein_repo_dir)
	execute '!git clone https://github.com/Shougo/dein.vim ' . s:dein_repo_dir
endif

" Required:
execute 'set runtimepath^=' . s:dein_repo_dir

" Required:
if dein#load_state(s:dein_dir)
	call dein#begin(s:dein_dir)

	" 管理するプラグインを記述したファイル
	let s:toml = s:rc_dir . '/.dein.toml'
	let s:lazy_toml = s:rc_dir . '/.dein_lazy.toml'

	" 読み込み，キャッシュは :call dein#clear_cache() で消せる
	call dein#load_toml(s:toml, {'lazy':0})
	call dein#load_toml(s:lazy_toml, {'lazy':1}) 
	" Required: 
	call dein#end() 
	call dein#save_state() 
endif 
" Required:
filetype plugin indent on

" If you want to install not installed plugins on startup.
if dein#check_install()
  call dein#install()
endif

"End dein Scripts-------------------------

set number
set backup
set backupdir=/tmp
set directory=/tmp
set undodir=/tmp
set tabstop=4
set shiftwidth=4
set softtabstop=0
set autoindent
set nowrap
set fenc=utf-8
set showmode
syntax on

" ESCでハイライトをオフ
nnoremap <silent> <ESC> <ESC>:noh<CR>
